file:
  location: /tmp

server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: 1234

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  datasource:
    url: jdbc:h2:mem:portaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  # enable H2 web console and set url for web console
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    show-sql: true
    generate-ddl: true

    # springboot-jpa LazyInitializationException
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true


logging:
  level:
    root: warn
    com.simple.portal: debug

